### PR TITLE
Do not destroy minions in bounce() if they're already dead

### PR DESCRIPTION
**Pull request by beheh**
This fixes The Skeleton Knight error when the hand is full and `bounce` tries to destroy the minion again.

Includes the tests from @oftc-ftw.

### CODE REVIEW

**Comment by jleclanche** [comment]
I don't know if this is the right fix. Let me think about it. I need to test it in HS.

**Comment by oftc-ftw** [comment]
I guess dead minions won't be enough: http://dpaste.com/0KBRHWA

**Comment by beheh** [comment]
Good point. So, there a few things here:
- is it always incorrect if a minions moves from a zone to the same zone?
- should destroy throw an error if a minion is already destroyed?
- should bounce be possible from anywhere but field and graveyard? What about discarded? What about hand?

**Comment by jleclanche** [comment]
The assert isn't actually required. I added it because when these situations arise, something *might* be wrong, or might be unoptimized, and it needs to be thought about. I'm fairly certain HS wouldn't error out in such a situation.

destroy() should definitely throw an error but it should also be implemented in Action, like how the other api calls work.

Part of the issue is that I would like to move "game rules" logic outside of the classes, to a more dsl-based definition. I tried doing something like this in fireplace.rules but it didn't really pan out... it's still used for Poisonous, but I wanted to use it for all the silenceable game tags basically. Maybe it's not a correct move, I don't know.

**Comment by beheh** [comment]
Let's track this at #249.

**Pull request closed without merging**
