### PR TITLE
More Cards

### PR DESCRIPTION
**Pull request by shinoi2**
Knowed issue: Some tests will fail under special circumstances.
* test_medivh cost(2) summon ”Wild Pyromancer“ or "Sorcerer's Apprentice”, test will be failed.
* "Molten Giant" cost 25 -> 20 make some test failed.
* prepare_game() will cause an unexpected error.

### CODE REVIEW

**Comment by tonyyyye** [comment]
test cases failed by CI.
Can you fix those or can you roll back to some previous submission that may pass this?
BTW flake8 and ci can be intergrated into your branch.

**Comment by shinoi2** [comment]
1. flake8 failed, it checks my code style and includes a lot of files. I don't cleanly know how to fix it.
2. test case failed, I will fix it in this weekend.

**Comment by tonyyyye** [comment]
When i have time i will help to check the flake8 issue.
Thanks for your great contribution.

**Comment by jleclanche** [comment]
@shinoi2 @tonyyyye sorry I'm quiet here, it's a busy week... I'll get to this pr

**Comment by shinoi2** [comment]
@jleclanche This PR is very dirty, do I need to organize it into several patches to submit?

**Comment by tonyyyye** [comment]
We've decided to split this PR into several smaller ones which are clear and easy for you to check and merge.

**Pull request closed without merging**
