### PR TITLE
Replace *_double amount multiplications by bitshifts

### LINKED ISSUE #234: Spellpower doubling is actually +100%, not x2
If a player has 2 Prophet Velen in play, then their spell damage and healing is x4. Right now this is coded such that you can only get x2.

https://www.youtube.com/watch?v=1Zav6Ubx3X0

### PR DESCRIPTION
**Pull request by beheh**
This PR:
- fixes #234 
- adds a second placeholder test for Velen
- adds tests for the various `*_double`-interactions

### CODE REVIEW

**Comment by beheh** [comment]
Ready to go.

**Comment by jleclanche** [comment]
Can you rebase please

**Comment by jleclanche** [comment]
Squash and gtm

**Comment by beheh** [comment]
We'll still have to revisit this as part of #238, but I'll push this for now since it's better than nothing.

**Pull request closed without merging**
