### PR TITLE
Add Inspire action and implement Void Crusher

### PR DESCRIPTION
**Pull request by beheh**
This PR:
- adds an `Inspire` action,
- changes hero powers to call  `Inspire` to trigger inspire scripts,
- implements Void Crusher

### CODE REVIEW

**Comment by jleclanche** [comment]
Seeing as wilfred and fist of jaraxxus are fairly new mechanics, please commit them separately.

**Comment by beheh** [comment]
@jleclanche I'm thinking about the Fist of Jaraxxus/discard stuff - normally events correctly don't go through to discarded cards, so `event=Discard().on` (like I'm currently trying it) might be a bad idea. What about adding a `discard=` script to make Fist of Jaraxxus and future cards like that work? We already have the game action `Discard`.
The alternative is making `Discard.broadcast` a special case which *additionally* targets the currently discarded card, but I don't really like that.

**Comment by beheh** [comment]
I've implemented `discard=`-script support now, do take a look at it.

**Comment by beheh** [comment]
Alright, all done from my side.

**Comment by beheh** [comment]
Moved the simpler stuff over to #145 now.

**Comment by beheh** [comment]
Currently blocked by #142.

**Comment by beheh** [comment]
Closing in favor of `Activate()` (see #142).

**Pull request closed without merging**
