### PR TITLE
Add Powershell equivalent to bootstrap.sh

### PR DESCRIPTION
**Pull request by liujimj**

### CODE REVIEW

**Comment by jleclanche** [comment]
Nice, thank you. Can you rename it to `powershell.ps1` and rebase please?

Also I'm not an expert at Powershell but it seems like some of those variables need to be quoted when invoked, like in bash, no? eg `git -C $HsdataDir` would fail if there's spaces in there?

**Comment by liujimj** [comment]
Renamed and just checked, looks like Powershell handles spaces in filenames elegantly because unlike Bash, not everything is a string.

Fiddling with git right now to figure the right invocation for the rebase.

**Comment by liujimj** [comment]
Ok, commit history should be clean now.

**Comment by jleclanche** [comment]
It's not, I'm still seeing merge commits. Try `git rebase -i upstream/master` (replace upstream by whatever the name of the  jleclanche/fireplace.git remote is).

**Comment by jleclanche** [comment]
To keep a single commit you can also pass `-i` to git rebase and replace `pick` by `fixup` for your last commit. Then `git push --force` to update the PR.

If it's too much trouble I'll do it for you but I'd rather keep commit authenticity.

**Comment by liujimj** [comment]
No, I agree that linearizing the commit history is both correct and my own responsibility.

I've fixed everything up (for real this time), please let me know if there's anything else.

**Comment by jleclanche** [comment]
I think you forgot to `git fetch` first, there was a commit since ;)

**Comment by liujimj** [comment]
If you mean I've missed a commit most recently, I'm not sure I see that -- CI shows this is up to date with base.

**Comment by jleclanche** [comment]
That's because it's up to date with your repository, but not jleclanche/fireplace. Try `git fetch upstream/master && git rebase upstream/master`?

**Comment by liujimj** [comment]
Very strange, my client was showing my branch was caught up to origin last time I pushed, and only now did it pick up that it was behind. In any case, github confirms I'm caught up now.

**Pull request merged**
