### PR TITLE
Add repeated test for full games

### PR DESCRIPTION
**Pull request by smallnamespace**

### CODE REVIEW

**Comment by jleclanche** [comment]
This is definitely not something I want to have to run every time I run tests. The tests taking <10 seconds to run is a good thing.

**Comment by smallnamespace** [comment]
@jleclanche 

Can we please talk about other good ways to catch problems like this https://github.com/jleclanche/fireplace/issues/290 automatically then?

While I strongly agree that having a fast test suite is generally a very good thing, I'm not sure that should automatically precludes having *any* test that takes longer. Otherwise, one would end up never writing integration-level or heavier tests at all.

Some alternatives are:
1) Reduce the number of iterations while still having a decent chance at catching random issues
2) Set up Travis to run this every X commits instead of every time (I think I know a way to do that)
3) Include this in the full test suite, but have Travis always skip it

Please let me know which of these might be acceptable.

**Comment by jleclanche** [comment]
Flaky tests are never helpful. I'd like to catch problems like that as well but it's not even a question of travis; I personally run the tests more often a minute than this can even run.

**Comment by pkappler** [comment]
I ran into the same errors as @smallnamespace when I tried simulating a large number of games.  Is the assertion invalid or is there a bug that needs fixing?

**Comment by smallnamespace** [comment]
@pkappler See https://github.com/jleclanche/fireplace/issues/290; this particular issue is fixed at https://github.com/jleclanche/fireplace/commit/f11ec370f1363a01598b8823c4331253d9c25f97.

Note that deep-cloning a game state will still result in errors due to global state; I'm going to start tracking down where.

**Comment by smallnamespace** [comment]
@jleclanche It sounds like your workflow heavily depends on having a fast suite of non-flakey unit tests, so I understand the hesitation.

That said, I think larger, potentially flaky tests that proactively search for issues is also a legitimate approach (the entire [Hypothesis library](https://hypothesis.readthedocs.org/en/latest/) can be said to rely on this premise), and I'd like the option to put together a smoke test suite at some point.

Closing for now, will revisit when I have additional candidate smoke tests.

**Pull request closed without merging**
