### PR TITLE
Implement Reliquary Seeker and add test

### PR DESCRIPTION
**Pull request by beheh**
Need to verify HS behaviour.

### CODE REVIEW

**Comment by jleclanche** [comment]
We just confirmed it should be `Count(FRIENDLY_MINIONS) == 7`.

**Comment by beheh** [comment]
Wait, but that doesn't work, since it's not added in `play` yet, right? At least my test is failing...

**Comment by jleclanche** [comment]
Yes it does. The battlecry happens after the minionis in play. Did you remove `- SELF`?

**Comment by jleclanche** [comment]
Travis looks fine here.

**Comment by beheh** [comment]
So we do `Count(FRIENDLY_MINIONS - SELF) == 6`?

**Pull request merged**
