### PR TITLE
Fix Holy Wrath and add test

### PR DESCRIPTION
**Pull request by beheh**
This PR:
- fixes Holy Wrath
- adds a test case

### CODE REVIEW

**Comment by beheh** [comment]
Works for the base functionality, but fails when the player is in fatigue.
When in fatigue a Draw() should occur for fatigue damage, and 0 damage dealt to the target.

**Comment by beheh** [comment]
We should also fix Count() to be consistent with Attr().

**Comment by jleclanche** [comment]
Do it in a `self.get_entities(source)` method on LazyNum, that way you get it in `Count` for free.

**Comment by beheh** [comment]
Alright, all done.

**Pull request merged**
