### PR TITLE
Adding Kobolds and Catacombs cards

### PR DESCRIPTION
**Pull request by RXGottlieb**

### CODE REVIEW

**Comment by SoManyPants** [comment]
Had trouble implementing:
Kobold Barbarian
Upgraded versions of Spellstones

**Comment by shinoi2** [comment]
Some help about spellstone:
1) In managers.py add spellstone_process_total defined
`GameTag.TAG_SCRIPT_DATA_NUM_2: "spellstone_process_total"`
2) In class Spell add spellstone count
`self.spellstone_process_total = int_property("spellstone_process_total")
self.spellstone_process = 0`
3) Create an action to implement upgrade spellstone

**Comment by jleclanche** [comment]
I don't think binding GameTag.TAG_SCRIPT_DATA_NUM_2 as specifically a spellstone property is a good idea. Those state trackers are generic, so there should be a generic way of tracking and saving state from cards.

**Comment by shinoi2** [comment]
I don't know why spellstone use GameTag.TAG_SCRIPT_DATA_NUM_2 to save these number. 
A generic way is change xml file, use SPELL_PROCESS_TOTAL to replace TAG_SCRIPT_DATA_NUM_2.
The other way is use hard code in card script to save these number.

**Comment by jleclanche** [comment]
TAG_SCRIPT_DATA_NUM_1 and TAG_SCRIPT_DATA_NUM_2 are generic state buckets for cards. They aren't just used by spellstones. To have fireplace work well with those we will need actions to update and retrieve state in those buckets.

**Comment by shinoi2** [comment]
Too old and has conflict, close it

**Pull request closed without merging**
