### PR TITLE
Weighted picker fixes

### PR DESCRIPTION
**Pull request by djkaty**
Fix type annotations
Fix regression where 2-item RandomIDs treated as Tuples instead of Lists (Tinkmaster Overspark test)
Remove 'if' optimizations in weighted_card_choice

### CODE REVIEW

**Comment by jleclanche** [comment]
Travis is failing.

**Comment by djkaty** [comment]
It's failing on the new cards

**Comment by smallnamespace** [comment]
Looks like git isn't happy with this -- did a rebase go wrong?

**Comment by djkaty** [comment]
Yeah I'm aware, I left it while I sought advice in the channel.

**Comment by jleclanche** [comment]
Cont. in #339

**Pull request closed without merging**
