### PR TITLE
Add test for Jeweled Scarab

### PR DESCRIPTION
**Pull request by smallnamespace**

### CODE REVIEW

**Comment by smallnamespace** [comment]
@jleclanche ok, I've moved and renamed the test

**Comment by beheh** [comment]
Can you still assert the discovered cards similar to Gorillabot and Ethereal Conjurer? Also, we usually omit the trailing full stop in our commit messages. Otherwise fine by me.

**Comment by smallnamespace** [comment]
@beheh I've edited the commit message, and revised the test as you suggested. Please take another look and merge at your leisure.

**Comment by beheh** [comment]
Landed as e8e738aea9c7476eb24a2965324b317fc0cbd17f. Thanks for your PR!

**Pull request closed without merging**
