### PR TITLE
Fix Blood Imp and update test

### LINKED ISSUE #231: Blood Imp gives buff to all friendly minions
Suggested fix:
``` python
# Blood Imp
class CS2_059:
	events = OWN_TURN_END.on(Buff(RANDOM(FRIENDLY_MINIONS - SELF), "CS2_059o"))
```

``` python
def test_blood_imp():
	game = prepare_game()
	wisp1 = game.current_player.give(WISP)
	wisp2 = game.current_player.give(WISP)
	imp = game.current_player.give("CS2_059")
	imp.play()
	assert imp.health == 1
	game.end_turn(); game.end_turn()

	assert imp.health == 1
	wisp1.play()
	wisp2.play()
	assert wisp1.health + wisp2.health == 2
	game.end_turn()
	assert wisp1.health + wisp2.health == 3

	assert imp.health == 1
	assert wisp1.atk == 1
	assert wisp2.atk == 1
```

### PR DESCRIPTION
**Pull request by beheh**
This PR:
- fixes Blood Imp giving +1 health to all minions instead of one
- attributes the commit to @Meerkov
- fixes #231

### CODE REVIEW

**Comment by jleclanche** [comment]
There's a selector `RANDOM_OTHER_FRIENDLY_MINIONS` you can use for this (see swordsmith).

**Comment by beheh** [comment]
Done.

**Comment by jleclanche** [comment]
@beheh Can you clean the test up so it uses player1 / player2 as well please? (in the same commit)

**Comment by beheh** [comment]
Sorry, I overlooked that. Done.

**Comment by jleclanche** [comment]
gtm

**Pull request merged**
