### PR TITLE
Make tests a python package

### PR DESCRIPTION
**Pull request by smallnamespace**

### CODE REVIEW

**Comment by jleclanche** [comment]
Why?

**Comment by smallnamespace** [comment]
I'll fix the test breakage, but as for why:

1. Python folks explicitly recommend it (http://python-packaging.readthedocs.org/en/latest/testing.html)
2. It's standard convention for Python (e.g. https://github.com/kennethreitz/requests/blob/master/tests/__init__.py)
3. I wanted to import tests.utils to do some stuff, and couldn't without mucking with the python path, which is ugly

**Comment by jleclanche** [comment]
You need to change the utils imports to .utils then.

What do you need in tests.utils? I could consider moving some to fireplace.utils

**Comment by smallnamespace** [comment]
`prepare_game` and `prepare_empty_game`. If you're willing to move them, I can bundle it into this commit (or a separate one).

**Comment by jleclanche** [comment]
Ok, will see - I'd need to clean them up.

For the time being I'm ok merging this once it passes travis.

**Comment by smallnamespace** [comment]
Since we're using pytest, is it important to keep the path manipulation in each of the tests? Running py.test from root should pick up both fireplace and tests as packages.

**Comment by jleclanche** [comment]
I never actually got pytest running fine from other directories, if you manage to fix that that's great

**Comment by smallnamespace** [comment]
Yes, `py.test` now runs fine from any CWD (as long as you point it to the tests directory)

**Comment by smallnamespace** [comment]
@jleclanche 

To make Travis happy with this change, we'll need to make a minor change to the Travis config. We can either:

1. Pass `--pyargs tests` to `py.test`
2. or, run `py.test` directly from the `build/lib` directory

**Comment by jleclanche** [comment]
Neither of those options are acceptable...

**Comment by smallnamespace** [comment]
Why?

**Comment by beheh** [comment]
>Running py.test from root should pick up both fireplace and tests as packages.

and
>I never actually got pytest running fine from other directories, if you manage to fix that that's great

This is not new. On my system I could always execute all tests by simply running `py.test` from root, or from anywhere if I pass the tests directory as param. I think it required `./setup.py develop` though.

**Comment by smallnamespace** [comment]
@beheh Yes, py.test now works from root even without running ./setup.py develop

@jleclanche Friendly ping -- I think we should change py.test invocation because the semantics are unchanged. It's just telling py.test to find from one location or the other, but both sets of test are identical.

**Comment by smallnamespace** [comment]
The more I think about this, the more I only prefer it if tests were under fireplace so it doesn't pollute the global package namespace. Dropping for now.

**Pull request closed without merging**
