### PR TITLE
Gangs - most of the cards

### PR DESCRIPTION
**Pull request by snowypowers**
Most of the easy to implement cards in Gangs :)

### CODE REVIEW

**Comment by judge2020** [comment]
So it looks like the Silvermoon Portal test fails if the random minion is Wild Pyro.

**Comment by jleclanche** [comment]
That's fine for now. We can figure out a better way to test it later.

**Comment by NightKev** [comment]
Typo in the "Lunar Visions" commit btw ("Test" instead of "Implement").

**Comment by snowypowers** [comment]
Spelling errors have been corrected. Will review Silvermoon Portal test seperately

**Pull request closed without merging**
