### PR TITLE
Make fireplace directly pip installable, including running bootstrap - #318

### PR DESCRIPTION
**Pull request by smallnamespace**

### CODE REVIEW

**Comment by jleclanche** [comment]
According to https://github.com/pypa/pip/issues/2023#issuecomment-55251358 `--process-dependency-links` is deprecated so I'm -1 on including it.

**Comment by smallnamespace** [comment]
Yes, but if you read down to the end, https://github.com/pypa/pip/issues/2023#issuecomment-76086349, they recognize the use case and are keeping it in until pip supports PEP 440 direct dependencies.

Right now, fireplace is not a well-behaved Python library with respect to being pip installable, and that sucks. To fix it, our choices are either:

- Bite the bullet and push fireplace and its deps into PyPI
- Use `--process-dependency-links` for now, and replace it with PEP 440 deps later

**Comment by jleclanche** [comment]
Ill put python-hearthstone on pypi.

**Comment by smallnamespace** [comment]
Awesome, I'll rework the last couple of commits then and ping when ready

**Comment by smallnamespace** [comment]
@jleclanche Please take another look

**Comment by jleclanche** [comment]
Bootstrap has been removed. Closing this.

**Pull request closed without merging**
