### PR TITLE
Implement negating minion IDs in RandomEntourage #225

### PR DESCRIPTION
**Pull request by smallnamespace**

### CODE REVIEW

**Comment by jleclanche** [comment]
Just in general please keep typing hints to their own commits.

**Comment by smallnamespace** [comment]
@jleclanche 
Please take another look.

**Comment by smallnamespace** [comment]
@jleclanche 

I've addressed all comments, fine if I land it?

**Comment by jleclanche** [comment]
Not yet, I'm doing some other work at the moment which I'd like to land first.

**Comment by smallnamespace** [comment]
@jleclanche Shall I resync to HEAD, or are we awaiting more changes?

**Comment by smallnamespace** [comment]
@jleclanche Please take another look

**Comment by shinoi2** [comment]
Too old and has conflict, close it.

**Pull request closed without merging**
