### PR TITLE
Fix new Warsong Commander and add test

### PR DESCRIPTION
**Pull request by beheh**
RIP Grim Patron.

### CODE REVIEW

**Comment by beheh** [comment]
I think @jleclanche wanted the old tests to go somewhere, like as test minions? We should talk about this soon.

**Comment by jleclanche** [comment]
Yeah I'm still working on custom cards.

**Comment by beheh** [comment]
I've renamed the old tests to `test_old_warsong_*` (the same as the file) to avoid a naming conflict. @jleclanche: Are you okay with this?

**Comment by jleclanche** [comment]
Yeah that's fine.

**Comment by jleclanche** [comment]
gtm now btw

**Pull request merged**
