### PR TITLE
Fix source of PLAY action blocks

### PR DESCRIPTION
**Pull request by djkaty**

### CODE REVIEW

**Comment by jleclanche** [comment]
Can you explain what this fixes?

**Comment by djkaty** [comment]
So basically the existing code creates blocks like this when a card is played:

                [Start ] PLAY: Index = 0, Source = 2, Target = 0
...
                [Start ] POWER: Index = -1, Source = 81, Target = 0
...
                [End   ]
...
                [End   ]

The source in the PLAY block is the player and the source in the POWER block is the card being played. In the real Hearthstone, when a card is played, the PLAY block uses the card entity ID as the source, not the player. Without this, many strange effects occur and stuff doesn't work properly. The code essentially changes these scenarios so that in the example blocks above ,the PLAY source would be 85 (the card entity ID) rather than the player.

**Comment by jleclanche** [comment]
Hmm, I think this might affect cards that play other cards.

**Comment by djkaty** [comment]
If it does it will only affect it in the client, not fireplace AFAIK. As always, my policy with this stuff is to do it a bit at a time and slowly refine it.

**Comment by shinoi2** [comment]
Too old

**Pull request closed without merging**
