### PR TITLE
Add test for Recombobulator on Molten Giant

### PR DESCRIPTION
**Pull request by oftc-ftw**
Recombobulator should morph the Molten Giant into another Molten Giant (cost 20)

### CODE REVIEW

**Comment by oftc-ftw** [comment]
Failure is caused by #177

**Comment by jleclanche** [comment]
Use `game.player1.hero.set_current_health(15)` instead of moonfires (setting it to 15 ensures that it should crash if it's wrong)

**Comment by oftc-ftw** [comment]
I don't know about the internals but are you sure `set_current_hero_health(15)` is the same thing as being damaged until 15 health? I feel setting the health is more like Lord Jaraxxus, which does not affect the Molten cost.

>     <oftc_ftw> okay, so if i play jaraxxus at 30 hp, i will have 15 hp but the molten will still cost 20 mana?
>     <Xinhuan> yes

**Comment by oftc-ftw** [comment]
Sorry, I just confirmed that `game.player1.hero.set_current_health(15)` does work as intended (i.e. like damage, see #179). Updated as requested.

**Pull request merged**
