### PR TITLE
Bump Python version up to 3.5

### PR DESCRIPTION
**Pull request by smallnamespace**

### CODE REVIEW

**Comment by jleclanche** [comment]
gtm but I'm leaving this PR open up until we actually depend on 3.5

**Comment by smallnamespace** [comment]
https://github.com/jleclanche/fireplace/pull/307 can depend on this, if I remove the forward type declarations. Want me to cherry-pick it into that PR?

**Comment by jleclanche** [comment]
Add "Closes #310" to the commit description so that it autocloses when merged.

**Comment by smallnamespace** [comment]
Done

**Pull request merged**
